/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddCardFormRequest
 */
public class AddCardFormRequestTest {
    private final AddCardFormRequest model = new AddCardFormRequest();

    /**
     * Model tests for AddCardFormRequest
     */
    @Test
    public void testAddCardFormRequest() {
        // TODO: test AddCardFormRequest
    }

    /**
     * Test the property 'checkoutAccount'
     */
    @Test
    public void checkoutAccountTest() {
        // TODO: test checkoutAccount
    }

    /**
     * Test the property 'checkoutAlgorithm'
     */
    @Test
    public void checkoutAlgorithmTest() {
        // TODO: test checkoutAlgorithm
    }

    /**
     * Test the property 'checkoutMethod'
     */
    @Test
    public void checkoutMethodTest() {
        // TODO: test checkoutMethod
    }

    /**
     * Test the property 'checkoutNonce'
     */
    @Test
    public void checkoutNonceTest() {
        // TODO: test checkoutNonce
    }

    /**
     * Test the property 'checkoutTimestamp'
     */
    @Test
    public void checkoutTimestampTest() {
        // TODO: test checkoutTimestamp
    }

    /**
     * Test the property 'checkoutRedirectSuccessUrl'
     */
    @Test
    public void checkoutRedirectSuccessUrlTest() {
        // TODO: test checkoutRedirectSuccessUrl
    }

    /**
     * Test the property 'checkoutRedirectCancelUrl'
     */
    @Test
    public void checkoutRedirectCancelUrlTest() {
        // TODO: test checkoutRedirectCancelUrl
    }

    /**
     * Test the property 'checkoutCallbackSuccessUrl'
     */
    @Test
    public void checkoutCallbackSuccessUrlTest() {
        // TODO: test checkoutCallbackSuccessUrl
    }

    /**
     * Test the property 'checkoutCallbackCancelUrl'
     */
    @Test
    public void checkoutCallbackCancelUrlTest() {
        // TODO: test checkoutCallbackCancelUrl
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

}
