/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Card
 */
public class CardTest {
    private final Card model = new Card();

    /**
     * Model tests for Card
     */
    @Test
    public void testCard() {
        // TODO: test Card
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'partialPan'
     */
    @Test
    public void partialPanTest() {
        // TODO: test partialPan
    }

    /**
     * Test the property 'expireYear'
     */
    @Test
    public void expireYearTest() {
        // TODO: test expireYear
    }

    /**
     * Test the property 'expireMonth'
     */
    @Test
    public void expireMonthTest() {
        // TODO: test expireMonth
    }

    /**
     * Test the property 'cvcRequired'
     */
    @Test
    public void cvcRequiredTest() {
        // TODO: test cvcRequired
    }

    /**
     * Test the property 'bin'
     */
    @Test
    public void binTest() {
        // TODO: test bin
    }

    /**
     * Test the property 'funding'
     */
    @Test
    public void fundingTest() {
        // TODO: test funding
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'cardFingerprint'
     */
    @Test
    public void cardFingerprintTest() {
        // TODO: test cardFingerprint
    }

    /**
     * Test the property 'panFingerprint'
     */
    @Test
    public void panFingerprintTest() {
        // TODO: test panFingerprint
    }

}
