/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetTokenRequest
 */
public class GetTokenRequestTest {
    private final GetTokenRequest model = new GetTokenRequest();

    /**
     * Model tests for GetTokenRequest
     */
    @Test
    public void testGetTokenRequest() {
        // TODO: test GetTokenRequest
    }

    /**
     * Test the property 'checkoutTokenizationId'
     */
    @Test
    public void checkoutTokenizationIdTest() {
        // TODO: test checkoutTokenizationId
    }

}
