/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentReportBySettlementIdRequest
 */
public class PaymentReportBySettlementIdRequestTest {
    private final PaymentReportBySettlementIdRequest model = new PaymentReportBySettlementIdRequest();

    /**
     * Model tests for PaymentReportBySettlementIdRequest
     */
    @Test
    public void testPaymentReportBySettlementIdRequest() {
        // TODO: test PaymentReportBySettlementIdRequest
    }

    /**
     * Test the property 'requestType'
     */
    @Test
    public void requestTypeTest() {
        // TODO: test requestType
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'reportFields'
     */
    @Test
    public void reportFieldsTest() {
        // TODO: test reportFields
    }

    /**
     * Test the property 'submerchant'
     */
    @Test
    public void submerchantTest() {
        // TODO: test submerchant
    }

}
