/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.suchventure.paytrail.client.model.Address;
import com.suchventure.paytrail.client.model.Callbacks;
import com.suchventure.paytrail.client.model.Customer;
import com.suchventure.paytrail.client.model.Item;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenPaymentRequest
 */
public class TokenPaymentRequestTest {
    private final TokenPaymentRequest model = new TokenPaymentRequest();

    /**
     * Model tests for TokenPaymentRequest
     */
    @Test
    public void testTokenPaymentRequest() {
        // TODO: test TokenPaymentRequest
    }

    /**
     * Test the property 'stamp'
     */
    @Test
    public void stampTest() {
        // TODO: test stamp
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'deliveryAddress'
     */
    @Test
    public void deliveryAddressTest() {
        // TODO: test deliveryAddress
    }

    /**
     * Test the property 'invoicingAddress'
     */
    @Test
    public void invoicingAddressTest() {
        // TODO: test invoicingAddress
    }

    /**
     * Test the property 'redirectUrls'
     */
    @Test
    public void redirectUrlsTest() {
        // TODO: test redirectUrls
    }

    /**
     * Test the property 'callbackUrls'
     */
    @Test
    public void callbackUrlsTest() {
        // TODO: test callbackUrls
    }

    /**
     * Test the property 'callbackDelay'
     */
    @Test
    public void callbackDelayTest() {
        // TODO: test callbackDelay
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
