/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenCustomerDetails
 */
public class TokenCustomerDetailsTest {
    private final TokenCustomerDetails model = new TokenCustomerDetails();

    /**
     * Model tests for TokenCustomerDetails
     */
    @Test
    public void testTokenCustomerDetails() {
        // TODO: test TokenCustomerDetails
    }

    /**
     * Test the property 'networkAddress'
     */
    @Test
    public void networkAddressTest() {
        // TODO: test networkAddress
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

}
