/*
 * Payment API
 * Paytrail Payment API 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.suchventure.paytrail.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.suchventure.paytrail.client.model.PaymentMethodGroupDataWithProviders;
import com.suchventure.paytrail.client.model.PaymentMethodProvider;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.suchventure.paytrail.client.JSON;

/**
 * List grouped providers response body
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-19T20:23:13.800614+03:00[Europe/Helsinki]", comments = "Generator version: 7.5.0")
public class GroupedPaymentProvidersResponse {
  public static final String SERIALIZED_NAME_TERMS = "terms";
  @SerializedName(SERIALIZED_NAME_TERMS)
  private String terms;

  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  private List<PaymentMethodGroupDataWithProviders> groups = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROVIDERS = "providers";
  @SerializedName(SERIALIZED_NAME_PROVIDERS)
  private List<PaymentMethodProvider> providers = new ArrayList<>();

  public GroupedPaymentProvidersResponse() {
  }

  public GroupedPaymentProvidersResponse terms(String terms) {
    this.terms = terms;
    return this;
  }

   /**
   * Localized text with a link to payment terms
   * @return terms
  **/
  @javax.annotation.Nonnull
  public String getTerms() {
    return terms;
  }

  public void setTerms(String terms) {
    this.terms = terms;
  }


  public GroupedPaymentProvidersResponse groups(List<PaymentMethodGroupDataWithProviders> groups) {
    this.groups = groups;
    return this;
  }

  public GroupedPaymentProvidersResponse addGroupsItem(PaymentMethodGroupDataWithProviders groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Payment method group data for all of groups that are included in the query
   * @return groups
  **/
  @javax.annotation.Nonnull
  public List<PaymentMethodGroupDataWithProviders> getGroups() {
    return groups;
  }

  public void setGroups(List<PaymentMethodGroupDataWithProviders> groups) {
    this.groups = groups;
  }


  public GroupedPaymentProvidersResponse providers(List<PaymentMethodProvider> providers) {
    this.providers = providers;
    return this;
  }

  public GroupedPaymentProvidersResponse addProvidersItem(PaymentMethodProvider providersItem) {
    if (this.providers == null) {
      this.providers = new ArrayList<>();
    }
    this.providers.add(providersItem);
    return this;
  }

   /**
   * A flat list of payment method providers
   * @return providers
  **/
  @javax.annotation.Nonnull
  public List<PaymentMethodProvider> getProviders() {
    return providers;
  }

  public void setProviders(List<PaymentMethodProvider> providers) {
    this.providers = providers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupedPaymentProvidersResponse groupedPaymentProvidersResponse = (GroupedPaymentProvidersResponse) o;
    return Objects.equals(this.terms, groupedPaymentProvidersResponse.terms) &&
        Objects.equals(this.groups, groupedPaymentProvidersResponse.groups) &&
        Objects.equals(this.providers, groupedPaymentProvidersResponse.providers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terms, groups, providers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupedPaymentProvidersResponse {\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    providers: ").append(toIndentedString(providers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("terms");
    openapiFields.add("groups");
    openapiFields.add("providers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("terms");
    openapiRequiredFields.add("groups");
    openapiRequiredFields.add("providers");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GroupedPaymentProvidersResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GroupedPaymentProvidersResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupedPaymentProvidersResponse is not found in the empty JSON string", GroupedPaymentProvidersResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GroupedPaymentProvidersResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GroupedPaymentProvidersResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GroupedPaymentProvidersResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("terms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terms").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("groups").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `groups` to be an array in the JSON string but got `%s`", jsonObj.get("groups").toString()));
      }

      JsonArray jsonArraygroups = jsonObj.getAsJsonArray("groups");
      // validate the required field `groups` (array)
      for (int i = 0; i < jsonArraygroups.size(); i++) {
        PaymentMethodGroupDataWithProviders.validateJsonElement(jsonArraygroups.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("providers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `providers` to be an array in the JSON string but got `%s`", jsonObj.get("providers").toString()));
      }

      JsonArray jsonArrayproviders = jsonObj.getAsJsonArray("providers");
      // validate the required field `providers` (array)
      for (int i = 0; i < jsonArrayproviders.size(); i++) {
        PaymentMethodProvider.validateJsonElement(jsonArrayproviders.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupedPaymentProvidersResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupedPaymentProvidersResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupedPaymentProvidersResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupedPaymentProvidersResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupedPaymentProvidersResponse>() {
           @Override
           public void write(JsonWriter out, GroupedPaymentProvidersResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupedPaymentProvidersResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupedPaymentProvidersResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupedPaymentProvidersResponse
  * @throws IOException if the JSON string is invalid with respect to GroupedPaymentProvidersResponse
  */
  public static GroupedPaymentProvidersResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupedPaymentProvidersResponse.class);
  }

 /**
  * Convert an instance of GroupedPaymentProvidersResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

